-- Run this in your IBM Db2 database to support saving /ai/orchestrate responses.
-- If you already have questions and stakeholder_responses, run only the ALTER and CREATE TABLE.

-- 1. Add phase column to stakeholder_responses (skip if you create tables from scratch below)
ALTER TABLE stakeholder_responses ADD phase VARCHAR(50) DEFAULT 'legacy';

-- 2. Create orchestrate_runs table (full run per question)
CREATE TABLE orchestrate_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    topic_reasoning CLOB,
    deep_analysis CLOB,
    assigned_agent_id VARCHAR(100),
    expertise_rationale CLOB,
    rag_context CLOB,
    full_response CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orchestrate_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id)
);

-- If you do not have questions/stakeholder_responses yet, run this first:
/*
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text VARCHAR(2048) NOT NULL,
    location VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stakeholder_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id BIGINT NOT NULL,
    phase VARCHAR(50) NOT NULL DEFAULT 'legacy',
    stakeholder_id VARCHAR(100) NOT NULL,
    stakeholder_role VARCHAR(255) NOT NULL,
    ai_agent_id VARCHAR(100) NOT NULL,
    answer CHAR(3) NOT NULL,
    confidence DECIMAL(5, 2),
    reasoning CLOB,
    raw_payload CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_question
        FOREIGN KEY (question_id)
        REFERENCES questions(id)
);
*/
